### ISSUE TITLE
\vtop alignment in l3galley unexpected

### ISSUE THREAD

**Issue by grizzilus** [latex3/svn-mirror#178]
While working with some code loosely based off of the stackexchange answer http://tex.stackexchange.com/questions/30410/another-body-text-in-the-margin/32752#32752 I encountered some unexpected alignment that comes from anything that loads `l3galley`.

I don't know if this is intended since I am still not 100% comfortable with all of the experimental packages but this code produces a result quite different from what is produced if the `l3galley` package is removed.

```latex
\documentclass{article}

\usepackage{l3galley}

\begin{document}

a\vtop{\hsize=1cm a}

\end{document}
```

**Comment by josephwright** [comment]
@davidcarlisle has found a LaTeX2e demo
```tex
\documentclass{article}
\usepackage{l3galley}
\begin{document}
a\parbox[t]{1cm}{a}
\end{document}
```
Reopening as a result.

**Comment by josephwright** [comment]
Two-part fix here: one for `l3galley`, one for the demo. In the galley code I'd missed a subtle point from `galley2` (@frankmittelbach's code). It's vital not to add any inter-paragraph space at the start of a galley level, so there needs to be an explicit test. An upcoming check-in fixes that.

At the same time, uncontrolled vertical boxes will not work with the galley: they _have_ to be proper galley levels. That's needed so that the galley knows that a new level has started. (I've taken this from Frank: I don't think there's a way to do the job without this.)

Fixing the example and patching the galley code for the present leads to
```tex
\documentclass{article}
\usepackage{color}
\usepackage{l3galley}
\ExplSyntaxOn
\cs_new_eq:NN \GALLEYLEVEL \galley_level:
% Use until the l3galley update, at least for testing
\cs_new_eq:NN \orig__galley_insert_vspace: \__galley_insert_vspace:
\cs_set_protected:Npn \__galley_insert_vspace:
  {
    \bool_if:NF\g__galley_begin_level_bool
      { \orig__galley_insert_vspace: }
  }
\ExplSyntaxOff
\begin{document}
a\parbox[t]{1cm}{\GALLEYLEVEL a}
\end{document}
```
Note that `color` is required here as it makes the `\parbox` 'coffin-like': there's a reset required by the galley that is built around having a colour group at the edges of the box, which coffins do automatically.
