### ISSUE TITLE
\box_resize_to_ht:Nn sets dimensions incorrectly

### ISSUE THREAD

**Issue by josephwright** [latex3/svn-mirror#202]
-------- Forwarded Message --------
Subject: \box_resize_to_ht:Nn (bug report)
Date: Mon, 26 Jan 2015 10:55:17 +0100
From: Alexander Grahn <A.Grahn@HZDR.DE>
Reply-To: Mailing list for the LaTeX3 project <LATEX-L@LISTSERV.UNI-HEIDELBERG.DE>
To: LATEX-L@LISTSERV.UNI-HEIDELBERG.DE

Good morning,

I have just noticed that \box_resize_to_ht:Nn forces the given box
into a square instead of scaling the width appropriately. The other,
\box_resize_to_wd:Nn works as expected as it preserves the original
aspect ratio:

  \documentclass{article}
  \usepackage{expl3}
  \usepackage{graphicx}
  \usepackage{mwe}
  
  \begin{document}
  \newsavebox\picbox
  \savebox\picbox{\includegraphics{example-image-a}}
  
  \typeout{orig. size: \the\wd\picbox\space X \the\ht\picbox}
  
  \ExplSyntaxOn
  \box_resize_to_ht:Nn\picbox{60pt}
  \ExplSyntaxOff
  \typeout{\string\box_resize_to_ht:Nn \the\wd\picbox\space X \the\ht\picbox}
  
  \savebox\picbox{\includegraphics{example-image-a}}
  \ExplSyntaxOn
  \box_resize_to_wd:Nn\picbox{60pt}
  \ExplSyntaxOff
  \typeout{\string\box_resize_to_wd:Nn \the\wd\picbox\space X \the\ht\picbox}
  
  \end{document}

Kind regards,
Alexander

**Comment by blefloch** [comment]
This issue makes me realize that we set dimensions inaccurately: the
height resulting from box_resize_to_ht is 60.00061pt instead of 60pt.
This is because we use (e)TeX to multiply the original ht dimension by
a real number, and (e)TeX rounds(?) the real number to the closest
multiple of 1/65536.  The scale factor here is ~0.2490666 and is
treated as ~0.2490692 (a multiple of 1/65536), which leads to a
too-big height.

Users may say "resize to 60pt" and get a box that is not 60pt high.
To fix it, it may be enough to just use multiplication from l3fp for
the final scaling in \__box_resize:N but maybe that's still a bit
risky.  The safest solution would be to keep track of dimensions that
are requested by the user, and make sure that that's what is obtain,
but that's more work.

**Comment by josephwright** [comment]
@blefloch  I'll adjust the code here: I think we want to stick with re-calculating the size as in reality we have to use a scale factor at the driver level so there may be a rounding situation even there.
