### ISSUE TITLE
l3build: Support for BibTeX

### ISSUE THREAD

**Issue by josephwright** [latex3/svn-mirror#208]
Currently, `l3build` supports MakeIndex and thanks to #207 the use of Biber. However, support for 'classical' BibTeX is missing. There are various sub-issues here, so this could be regarded as a meta-issue. Things to think about:

 - BibTeX databases for building docs. These can be handled with something like

        demofiles    = {"*.bib"}
        typesetfiles = {"*.tex"}
        typesetsuppfiles = {"*.bib"}

 which I've done in [`biblatex-ieee`](https://github.com/josephwright/biblatex-ieee) and will do in my other  `biblatex` styles as needed, but this is a bit of a hack. We could just add a `bibfiles`/`bibtexfiles` setting except ...

 - BibTeX databases that go into the `bibtex/bib` tree. These are much rarer than those going into the doc tree: perhaps we simply want to leave this alone?

 - Running BibTeX. Presumably we don't want to support the full range of things people do with BibTeX  (per chapter, per section, ...) but probably do want a basic 'run BibTeX' setting. Unlike Biber, this can't be picked up by looking for a specific file: do we want to parse the `.aux` looking for `\citation`?

 - BibTeX style files. These come with some packages and may be unpacked or given 'as is'. Probably we just need a good setting name here: `bibstylefiles` perhaps?

I'm hoping @dffischer might have some thoughts here in addition to the team members and perhaps @paulocereda!

**Comment by dffischer** [comment]
#### Resource Location

From a semantic view, I think it is totally fine to consider BibTeX databases and styles as support files for typesetting.

However, in one of my own projects, I include documented tests in the documentation. So `supportdir` is already set to `testfiledir` and I cannot point it to the directory the `.bib` is located also.

It could be useful for such cases to turn `supportdir` into an array, so that support files can be looked up from multiple locations. This would be easy to do using the `locate` function. This also allows for collecting BibTeX resources from multiple locations. A clear distinction what to copy when is still possible through the various `*suppfiles` variables.


#### Checking for BibTeX

Parsing the `.aux` for `\citation` should be the appropriate strategy to determine whether `bibtex` has to be run. Doing so would be a one liner using `os.execute` and `grep` as far as Linux is concerned. Fortunately, Windows seems to have something similar called [findstr](https://www.microsoft.com/resources/documentation/windows/xp/all/proddocs/en-us/findstr.mspx?mfr=true). A wrapper function like it is already implemented for `diff` could solve this.
