### ISSUE TITLE
incorrect rounding in l3fp

### ISSUE THREAD

**Issue by u-fischer** [latex3/svn-mirror#222]
The rounding function doesn't work correctly for 2 (tested with a current texlive 2015):

~~~~~~
\documentclass{article}
\usepackage{expl3}
\begin{document}
\ExplSyntaxOn

\fp_eval:n{round(1.115,2)}\par %OK = 1.12
\fp_eval:n{round(1.125,2)}\par %wrong = 1.12 (instead of 1.13
\fp_eval:n{round(1.135,2)}     %OK  = 1.14 

\par
\fp_eval:n{round(1.15,1)}\par %OK = 1.2
\fp_eval:n{round(1.25,1)}\par %wrong = 1.2 (instead of 1.3
\fp_eval:n{round(1.35,1)}     %OK  = 1.4

\ExplSyntaxOff
\end{document}
~~~~~~
![round](https://cloud.githubusercontent.com/assets/4047173/8594798/a9cec020-2644-11e5-9c55-870c7b68c1bc.PNG)

**Comment by josephwright** [comment]
Clearly not right: I think @blefloch  is best placed to handle this :-)

**Comment by davidcarlisle** [comment]
Bruno can give authoritative answer, but is that wrong? It looks OK to me
with 5 rounding to even.

**Comment by u-fischer** [comment]
@davidcarlisle Well it is an even/odd problem. But I certainly don't think that is correct that the end number 5 is rounded down in some cases and rounded up in others. Or do you think this is ok:

~~~~~
\fp_eval:n{round(25,-1)}\par     %= 20
\fp_eval:n{round(15,-1)}\par     %= 20
~~~~~

**Comment by davidcarlisle** [comment]
On 9 July 2015 at 13:42, u-fischer <notifications@github.com> wrote:

> @davidcarlisle <https://github.com/davidcarlisle> Well it is an even/odd
> problem. But I certainly don't think that is correct that the end number 5
> is rounded down in some cases and rounded up in others. Or do you think
> this is ok:
>
> \fp_eval:n{round(25,-1)}\par     %= 20
> \fp_eval:n{round(15,-1)}\par     %= 20
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/latex3/svn-mirror/issues/222#issuecomment-119948759>.
>

Yes that's the behaviour I would expect from round and I see we even
document it:-)


· round yields the multiple of 10n closest to x, and if x is half-way
between two
  such multiples, the even multiple is chosen ("ties to even");

see also

https://en.wikipedia.org/wiki/Rounding#Round_half_to_even

David

**Comment by u-fischer** [comment]
@davidcarlisle OK looking around I also found the "round to even system". But that's not how we do it in business :-((  My last bill is wrong (by a cent ...)

But I understand the rationale and think I will simply have to adapt my code.

**Comment by josephwright** [comment]
@u-fischer  Am I OK to close then? Rounding is complicated :-) (I have much the same going on in `siunitx`, it's just that the standard setting is 'round down' even though that introduces some bias.)

**Comment by u-fischer** [comment]
@josephwright: Yes you can close it. But perhaps you could add a remark about the "round to even" at the begin of the l3fp doc. It says "round(x, n) rounds to closest" there and this put me on the wrong track.

**Comment by josephwright** [comment]
OK, I'll tweak the docs

**Comment by blefloch** [comment]
So as David says, this is not a bug.  `l3fp` rounds ties to even, as this is the standard rounding for IEEE-754 (2008) compliant floating points, which avoids bias and helps stabilise various algorithms.  There would be nothing wrong however with providing a variant of `round` that rounds ties towards infinity, or towards minus infinity, or towards zero.  Note I'm talking about ties (compare with `ceil`, `floor`, and `trunc`).  The only question is how to call these new functions round-to-nearest-ties-to-even (current `round`), round-to-nearest-ties-to-infinity, round-to-nearest-ties-to-minus-infinity, and round-to-nearest-ties-to-zero.  Any suggestion?

Before that is available, rounding to closest with ties rounded away from zero (I think that's what you want) can be done by

    \cs_new:Npn \my_round_ties_away:nn #1#2
      { \__my_round_ties_away:fn { \fp_eval:n {#1} } #2 }
    \cs_new:Npn \__my_round_ties_away:nn #1#2
      {
        \fp_compare:nTF { #1 < 0 } { floor } { ceil }
        (.5 * trunc(2*#1, #2), #2)
      }
    \cs_generate_variant:Nn \__my_round_ties_away:nn { f }

The code is a bit awkward because there is not `round away from zero` (the opposite of `trunc` which is `round towards zero`).  Perhaps that would be a sensible addition, but again what name? `away`?


As a site note, every inexact result (e.g. when multiplying numbers with many significant digits) is rounded to nearest with ties to even.  There is some very low-level support for changing the rounding mode (make it do like ceil, floor, trunc instead of round), but absolutely no way of accessing it at the user level.

 the standard suggests to make some tools available to

**Comment by blefloch** [comment]
@u-fischer With the development version of the code you can now do `round(1.23*3.45, 2, +inf)` to round to two decimal places with ties rounded up as you seem to want.  Once it is sent to CTAN (or before), I'd be grateful if you can thoroughly test, and then you can use it in your invoices.

**Comment by josephwright** [comment]
@blefloch  Should I send to CTAN?

**Comment by blefloch** [comment]
@josephwright I'd rather wait until something is decided concerning `\@sanitize` (cf issue 45 and my latest commit), but if you want, you can.
