### ISSUE TITLE
better \bool_show:N message

### ISSUE THREAD

**Issue by u-fischer** [latex3/svn-mirror#229]
When using `\bool_show:N` inside some command one can't see the name of bool variable involved:
As an example with the following document neither log nor terminal says anything about `\l_tmpa_bool`, while the other variable names are all there-

~~~~~

\documentclass{article}
\usepackage{expl3}
\begin{document}
\ExplSyntaxOn
\cs_new:Nn \uf_test_show: {
\int_show:N  \l_tmpa_int
\prop_show:N \l_tmpa_prop
\bool_show:N \l_tmpa_bool
\dim_show:N  \l_tmpa_dim
\clist_show:N\l_tmpa_clist
\seq_show:N  \l_tmpa_seq }

\uf_test_show:
\ExplSyntaxOff

\end{document}
~~~~~

**Comment by blefloch** [comment]
The fix should be something like changing `\bool_show:n {#1}` to `\__msg_show_variable:n { > \token_to_str:N #1 = \bool_if:NTF #1 { true } { false } }` in the definition of `\bool_show:N`, but I'll only do it next week, sorry.

**Comment by blefloch** [comment]
@u-fischer Let me take advantage of this issue to ask what `\tl_show:N` should show.  Currently it shows something like

    > \l_tmpa_tl=macro:
    ->foobar.
    <recently read> }

Should I just do

    > \l_tmpa_tl=foobar.
    <recently read> }

**Comment by josephwright** [comment]
@blefloch  I guess if we want to be 'self contained' then it would be nice :-) Is it doable, though?

**Comment by u-fischer** [comment]
@blefloch: I certainly like the neat messages of the more complicated data structures (`The property list \l_tmpa_prop is empty`). But I don't want to be greedy, `> 0. <argument> \l_tmpa_int  `  is okay too.

**Comment by blefloch** [comment]
@josephwright: totally doable.  Since we line-wrap the tl's content `\tl_show:N` does not use the primitive `\show`, so `macro:->` is added artificially.  I probably was too conservative in the change of output back then.

@u-fischer: It's actually not hard to have something like `>\l_tmpa_int=0.`  Probably the reason I didn't do that is that then we need to worry about line wrapping for very long csnames, in particular when showing a `skip` with both `plus` and `minus` parts.  With the current code, TeX is in charge of displaying the csname in whatever way it likes.

**Comment by blefloch** [comment]
If there is no objection, I will move the implementation of all `_show:N` and `_log:N` commands to the same file (presumably `l3msg.dtx`), as it is currently quite painful to keep the various implementations in sync.  The implementations don't use internals of their respective datatypes (e.g., `\prop_show:N` is based on `\prop_map_function:NN`).

**Comment by blefloch** [comment]
I just did a major internal rewrite of how variables and expressions are shown or logged, but keeping the code scattered throughout modules ended up being easier (since there are 'show' commands defined outside `l3kernel`).

The only remaining question related to this issue is whether `\bool_show:n` (or `int`, `dim`, `skip`, `muskip`) should show the original expression alongside the result.  This is easy to code, and will lead to more informative logs, but perhaps that is too verbose in practice?
